name: Build AUModFramework
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ninja
        run: brew install ninja

      - name: Clone & Build Dobby
        run: |
          git clone https://github.com/jmpews/Dobby
          cd Dobby && mkdir build && cd build
          cmake .. -G Ninja \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_SYSTEM_PROCESSOR=arm64 \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 \
            -DCMAKE_BUILD_TYPE=Release \
            -DdobbySharedLibrary=OFF
          ninja

      - name: Build AUModFramework
        run: |
          export DOBBY_DIR=$GITHUB_WORKSPACE/Dobby/build
          cd $GITHUB_WORKSPACE
          make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AUMF-dylibs
          path: |
            build/AUModFramework.dylib
            build/ExampleMod.dylib
